version: "3"

env:
  API_HOST: "localhost"
  API_PORT: "8000"
  API_BASE_URL: '{{.API_BASE_URL | default "http://localhost:8000"}}'

tasks:
  # Server
  dev:
    desc: "FastAPI をローカルで実行 (reload)"
    cmds:
      - uv run uvicorn app.main:app --reload --host ${API_HOST} --port ${API_PORT}

  run:
    desc: "本番起動 (no reload)"
    env:
      LOG_LEVEL: "INFO"
      ENVIRONMENT: "prod"
    cmds:
      - uv run uvicorn app.main:app --host 0.0.0.0 --port ${API_PORT:-8080}

  health:
    desc: "GET /"
    cmds:
      - curl -s ${API_BASE_URL} | jq .

  otel:
    desc: "OTEL endpoint 確認"
    cmds:
      - echo $OTEL_EXPORTER_OTLP_ENDPOINT


  # Todo API
  todo:list:
    desc: "GET /todos"
    cmds:
      - curl -s ${API_BASE_URL}/todos/ | jq .

  todo:create:
    desc: "POST /todos (id=?, title=?, done=?)"
    vars:
      id:    '{{.id | default 1}}'
      title: '{{.title | default "no title"}}'
      done:  '{{.done | default false}}'
    cmds:
      - |
        curl -s -X POST ${API_BASE_URL}/todos/ \
        -H "Content-Type: application/json" \
        -d "{\"id\":{{.id}},\"title\":\"{{.title}}\",\"done\":{{.done}}}" \
        | jq .

  todo:update:
    desc: "PATCH /todos/{id} (usage: task todo:update id=1 DATA='{\"title\":\"hello\",\"done\":true}')"
    vars:
      id: '{{.id | default "1"}}'
    cmds:
      - |
        DATA='{{.DATA | default "{\"done\":true}"}}'
        curl -s -X PATCH ${API_BASE_URL}/todos/{{.id}} \
        -H "Content-Type: application/json" \
        -d "$DATA" \
        | jq .

  todo:delete:
    desc: "DELETE /todos/{id} (usage: task todo:delete id=1)"
    vars:
      id: '{{.id | default "1"}}'
    cmds:
      - |
        curl -s -X DELETE ${API_BASE_URL}/todos/{{.id}} \
        | jq .
