version: "3"

env:
  API_HOST: "localhost"
  API_PORT: "8000"

tasks:
  # Server
  dev:
    desc: "FastAPI をローカルで実行 (reload)"
    cmds:
      - uv run uvicorn app.main:app --reload --host ${API_HOST} --port ${API_PORT}

  run:
    desc: "本番起動 (no reload)"
    env:
      LOG_LEVEL: "INFO"
      ENVIRONMENT: "prod"
    cmds:
      - uv run uvicorn app.main:app --host 0.0.0.0 --port ${API_PORT:-8080}

  health:
    desc: "GET /"
    cmds:
      - curl -s http://${API_HOST}:${API_PORT} | jq .

  otel:
    desc: "OTEL endpoint 確認"
    cmds:
      - echo $OTEL_EXPORTER_OTLP_ENDPOINT


  # Todo API
  todo:list:
    desc: "GET /todos"
    cmds:
      - curl -s http://${API_HOST}:${API_PORT}/todos | jq .


  todo:create:
    desc: "POST /todos (id=?, title=?, done=?)"
    vars:
      id:    '{{.id | default 1}}'
      title: '{{.title | default "no title"}}'
      done:  '{{.done | default false}}'
    cmds:
      - |
        curl -s -X POST http://${API_HOST}:${API_PORT}/todos \
        -H "Content-Type: application/json" \
        -d "{\"id\":{{.id}},\"title\":\"{{.title}}\",\"done\":{{.done}}}" \
        | jq .


  todo:update:
    desc: "PATCH /todos/{id}"
    vars:
      id:   '{{.id | default 1}}'
      done: '{{.done | default true}}'
    cmds:
      - |
        curl -s -X PATCH http://${API_HOST}:${API_PORT}/todos/{{.id}} \
        -H "Content-Type: application/json" \
        -d "{\"done\": {{.done}} }" \
        | jq .


  todo:delete:
    desc: "DELETE /todos/{id}"
    vars:
      id: '{{.id | default 1}}'
    cmds:
      - |
        curl -s -X DELETE http://${API_HOST}:${API_PORT}/todos/{{.id}} \
        | jq .
